#! /usr/bin/env bash

VIRTUAL_ENV="venv"
REQUIREMENTS_FILE="requirements.txt"
PROGRAM_NAME="price_watchdog.py"

cd "$(dirname "$0")"
if [[ ! -d "${VIRTUAL_ENV}" ]] ; then
    echo "Creating virtual environment..."
    python3 -m venv "${VIRTUAL_ENV}"
    source venv/bin/activate

    echo "Installing dependencies..."
    pip3 install --requirement "${REQUIREMENTS_FILE}" > /dev/null
else
    source venv/bin/activate
fi

python3 "${PROGRAM_NAME}" ${@}
